---
### Playbook for configuring a server to work with Scriter
#
# Be sure to change the password in vars when deploying to production
#

- hosts: localhost 
  remote_user: root
  vars:
    db_username: scriter
    db_password: scriter_pass
    web_db: scriter_web
  tasks:
    # Install Pip, Pyscopg2, and Postgres
    - name: pip install
      apt:
        name: python-pip
    - name: psycopg2 prereq (libpq-dev)
      apt:
        name: libpq-dev
    - name: psycopg2 install
      apt:
        name: python-psycopg2
    - name: postgresql install
      apt:
        name: postgresql
        state: latest
    - name: postgresql activate
      service:
        name: postgresql
        state: started

    # Configure Python libraries in a Virtualenv
    - name: virtualenv install
      apt:
        name: virtualenv
    - name: install Python libs
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        virtualenv: "{{ playbook_dir }}/../venv"
        virtualenv_python: python3

    # Configure Postgres DB's for project
    - name: postgresql database (scriter_ingest)
      become: true
      become_user: postgres
      postgresql_db: 
        name: scriter_ingest
    - name: postgresql database (scriter_web)
      become: true
      become_user: postgres
      postgresql_db:
        name: scriter_web
    - name: postgresql service account ingest
      become: true
      become_user: postgres
      postgresql_user:
        db: scriter_ingest
        name: "{{ db_username }}"
        password: "{{ db_password}}"
        priv: "ALL"
        encrypted: yes
    - name: postgresql service account web
      become: true
      become_user: postgres
      postgresql_user:
        db: scriter_web
        name: "{{ db_username }}"
        password: "{{ db_password}}"
        priv: "ALL"
        encrypted: yes

    # Configure Django environment variables
    - name: make profile.d/scriter.sh
      file:
        path: /etc/profile.d/scriter.sh
        state: touch
        mode: '0644'
    - name: add DB username to profile.d
      lineinfile:
        path: /etc/profile.d/scriter.sh
        line: "export DB_USER={{ db_username }}"
    - name: add DB password to profile.d
      lineinfile:
        path: /etc/profile.d/scriter.sh
        line: "export DB_PASS={{ db_password }}"
    - name: add DB name to profile.d
      lineinfile:
        path: /etc/profile.d/scriter.sh
        line: "export DB_NAME={{ web_db }}"

    # Install Apache webserver
    - name: apache install
      apt:
        name: apache2
        state: latest
    - name: apache activate
      service:
        name: apache2
        state: started

    # Configure a service account
    - name: add service account
      user: 
        name: scriter
        shell: /bin/bash
    - name: change directory ownership
      file:
        name: "{{ playbook_dir }}/.."
        owner: scriter
        group: scriter
        recurse: yes
    - name: source virtualenv
      lineinfile:
        path: /home/scriter/.bashrc
        line: "source {{ playbook_dir }}/../venv/bin/activate"
    - name: source env variables
      lineinfile:
        path: /home/scriter/.bashrc
        line: "source /etc/profile.d/scriter.sh"
